/*
 * accessPointConfPanel.java
 *
 * Created on 24 de Novembro de 2005, 19:35
 */

package gui;

/**
 *
 * @author  Helen Peters
 */
public class AccessPointConfPanel extends javax.swing.JPanel {
    
    /** Creates new form accessPointConfPanel */
    public AccessPointConfPanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        accessPointApplicationComboBox = new javax.swing.JComboBox();
        accessPointNumberLabel = new javax.swing.JLabel();
        accessPointNumberTextField = new javax.swing.JTextField();
        accessPointLocationLabel = new javax.swing.JLabel();
        accessPointEnergyLabel = new javax.swing.JLabel();
        accessPointEnergyTextField = new javax.swing.JTextField();
        joulesLabel = new javax.swing.JLabel();
        accessPointApplicationLabel = new javax.swing.JLabel();
        accessPointLocationComboBox = new javax.swing.JComboBox();
        accessPointTransmissionRangeLabel = new javax.swing.JLabel();
        accessPointTransmissionRangeTextField = new javax.swing.JTextField();
        metersLabel = new javax.swing.JLabel();

        setLayout(null);

        setBackground(new java.awt.Color(240, 238, 231));
        accessPointApplicationComboBox.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointApplicationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Application/AccessPointApplication" }));
        accessPointApplicationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessPointApplicationComboBoxActionPerformed(evt);
            }
        });

        add(accessPointApplicationComboBox);
        accessPointApplicationComboBox.setBounds(210, 140, 270, 22);

        accessPointNumberLabel.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointNumberLabel.setText("ACCESS POINT NUMBER: ");
        add(accessPointNumberLabel);
        accessPointNumberLabel.setBounds(20, 20, 125, 14);

        accessPointNumberTextField.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointNumberTextField.setText("1");
        accessPointNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessPointNumberTextFieldActionPerformed(evt);
            }
        });
        accessPointNumberTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accessPointNumberTextFieldFocusLost(evt);
            }
        });

        add(accessPointNumberTextField);
        accessPointNumberTextField.setBounds(210, 20, 270, 19);

        accessPointLocationLabel.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointLocationLabel.setText("ACCESS POINT LOCATION:");
        add(accessPointLocationLabel);
        accessPointLocationLabel.setBounds(20, 60, 132, 14);

        accessPointEnergyLabel.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointEnergyLabel.setText("INITIAL ENERGY:");
        add(accessPointEnergyLabel);
        accessPointEnergyLabel.setBounds(20, 100, 81, 14);

        accessPointEnergyTextField.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointEnergyTextField.setText("1000");
        accessPointEnergyTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessPointEnergyTextFieldActionPerformed(evt);
            }
        });
        accessPointEnergyTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accessPointEnergyTextFieldFocusLost(evt);
            }
        });

        add(accessPointEnergyTextField);
        accessPointEnergyTextField.setBounds(210, 100, 220, 19);

        joulesLabel.setFont(new java.awt.Font("Arial", 0, 11));
        joulesLabel.setText("Joules");
        add(joulesLabel);
        joulesLabel.setBounds(450, 100, 31, 20);

        accessPointApplicationLabel.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointApplicationLabel.setText("ACCESS POINT APPLICATION:");
        add(accessPointApplicationLabel);
        accessPointApplicationLabel.setBounds(20, 140, 146, 14);

        accessPointLocationComboBox.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointLocationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CENTER", "UP LEFT CORNER", "DOWN LEFT CORNER", "UP RIGHT CORNER", "DOWN RIGHT CORNER", "GRID", "RANDOM" }));
        accessPointLocationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessPointLocationComboBoxActionPerformed(evt);
            }
        });

        add(accessPointLocationComboBox);
        accessPointLocationComboBox.setBounds(210, 60, 270, 22);

        accessPointTransmissionRangeLabel.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointTransmissionRangeLabel.setText("TRANSMISSION RANGE");
        add(accessPointTransmissionRangeLabel);
        accessPointTransmissionRangeLabel.setBounds(20, 180, 115, 14);

        accessPointTransmissionRangeTextField.setFont(new java.awt.Font("Arial", 0, 11));
        accessPointTransmissionRangeTextField.setText("100");
        accessPointTransmissionRangeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessPointTransmissionRangeTextFieldActionPerformed(evt);
            }
        });
        accessPointTransmissionRangeTextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                accessPointTransmissionRangeTextFieldFocusLost(evt);
            }
        });

        add(accessPointTransmissionRangeTextField);
        accessPointTransmissionRangeTextField.setBounds(210, 180, 220, 19);

        metersLabel.setFont(new java.awt.Font("Arial", 0, 11));
        metersLabel.setText("meters");
        add(metersLabel);
        metersLabel.setBounds(450, 180, 33, 20);

    }// </editor-fold>//GEN-END:initComponents

    private void accessPointTransmissionRangeTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accessPointTransmissionRangeTextFieldFocusLost
          javax.swing.JTextField textField = (javax.swing.JTextField) evt.getSource();
          String content = textField.getText();
          if (content.length() != 0) {
            try {
              double aux = Double.parseDouble(content);
              MainFrame.getTcl().setAccessPointTransmissionRange(aux);
            } catch (NumberFormatException nfe) {
              textField.requestFocus();
            }
          }
    }//GEN-LAST:event_accessPointTransmissionRangeTextFieldFocusLost

    private void accessPointEnergyTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accessPointEnergyTextFieldFocusLost
          javax.swing.JTextField textField = (javax.swing.JTextField) evt.getSource();
          String content = textField.getText();
          if (content.length() != 0) {
            try {
              double aux = Double.parseDouble(content);
              MainFrame.getTcl().setAccessPointEnergy(aux);
            } catch (NumberFormatException nfe) {
              textField.requestFocus();
            }
          }
    }//GEN-LAST:event_accessPointEnergyTextFieldFocusLost

    private void accessPointNumberTextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_accessPointNumberTextFieldFocusLost
          javax.swing.JTextField textField = (javax.swing.JTextField) evt.getSource();
          String content = textField.getText();
          if (content.length() != 0) {
            try {
              int aux = Integer.parseInt(content);
              MainFrame.getTcl().setAccessPointNumber(aux);
            } catch (NumberFormatException nfe) {
              textField.requestFocus();
            }
          }
    }//GEN-LAST:event_accessPointNumberTextFieldFocusLost

    private void accessPointNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessPointNumberTextFieldActionPerformed

        int aux = 0;
        String s = accessPointNumberTextField.getText();
        if (s.length() != 0) {
            try {
                aux = Integer.parseInt(s);
                MainFrame.getTcl().setAccessPointNumber(aux);
            } catch (NumberFormatException nfe) {
                getToolkit().beep();
                accessPointNumberTextField.requestFocus();
            }
        }
        MainFrame.setXMLSaved(false);
    }//GEN-LAST:event_accessPointNumberTextFieldActionPerformed

    private void accessPointLocationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessPointLocationComboBoxActionPerformed

        MainFrame.getTcl().setAccessPointLocation((String) accessPointLocationComboBox.getSelectedItem());
        MainFrame.setXMLSaved(false);
    }//GEN-LAST:event_accessPointLocationComboBoxActionPerformed

    private void accessPointEnergyTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessPointEnergyTextFieldActionPerformed

        double aux = 0;
        String s = accessPointEnergyTextField.getText();
        if (s.length() != 0) {
            try {
                aux = Double.parseDouble(s);
                MainFrame.getTcl().setAccessPointEnergy(aux);
            } catch (NumberFormatException nfe) {
                getToolkit().beep();
                accessPointEnergyTextField.requestFocus();
            }
        }        
        MainFrame.setXMLSaved(false);
    }//GEN-LAST:event_accessPointEnergyTextFieldActionPerformed

    private void accessPointApplicationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessPointApplicationComboBoxActionPerformed

        MainFrame.getTcl().setAccessPointApplication((String) accessPointApplicationComboBox.getSelectedItem());
        MainFrame.setXMLSaved(false);
    }//GEN-LAST:event_accessPointApplicationComboBoxActionPerformed

    private void accessPointTransmissionRangeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessPointTransmissionRangeTextFieldActionPerformed

        double aux = 0;
        String s = accessPointTransmissionRangeTextField.getText();
        if (s.length() != 0) {
            try {
                aux = Double.parseDouble(s);
                MainFrame.getTcl().setAccessPointTransmissionRange(aux);
            } catch (NumberFormatException nfe) {
                getToolkit().beep();
                accessPointTransmissionRangeTextField.requestFocus();
            }
        }           
        MainFrame.setXMLSaved(false);
    }//GEN-LAST:event_accessPointTransmissionRangeTextFieldActionPerformed
 
    private Object makeObj(final String item)  {
     return new Object() { public String toString() { return item; } };
   }    

    private void setAccessPointNumberTextField(String s){        
        accessPointNumberTextField.setText(s);        
    }

    private void setAccessPointLocationComboBox(String s) {       
        accessPointLocationComboBox.addItem(makeObj(s));
        accessPointLocationComboBox.setSelectedItem(s);
    }  
    
    private void setAccessPointEnergyTextField(String s){        
        accessPointEnergyTextField.setText(s);        
    }
            
    private void setAccessPointApplicationComboBox(String s) {       
        accessPointApplicationComboBox.addItem(s);
        accessPointApplicationComboBox.setSelectedItem(s);
    }  
            
    private void setAccessPointTransmissionRangeTextField(String s){        
        accessPointTransmissionRangeTextField.setText(s);        
    }
    
    public void updateFields(TclFields tcl){
        setAccessPointLocationComboBox(tcl.getAccessPointLocation());
        setAccessPointNumberTextField(String.valueOf(tcl.getAccessPointNumber()));
        setAccessPointEnergyTextField(String.valueOf(tcl.getAccessPointEnergy()));     
        setAccessPointApplicationComboBox(tcl.getAccessPointApplication());      
        setAccessPointTransmissionRangeTextField(String.valueOf(tcl.getAccessPointTransmissionRange()));       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accessPointApplicationComboBox;
    private javax.swing.JLabel accessPointApplicationLabel;
    private javax.swing.JLabel accessPointEnergyLabel;
    private javax.swing.JTextField accessPointEnergyTextField;
    private javax.swing.JComboBox accessPointLocationComboBox;
    private javax.swing.JLabel accessPointLocationLabel;
    private javax.swing.JLabel accessPointNumberLabel;
    private javax.swing.JTextField accessPointNumberTextField;
    private javax.swing.JLabel accessPointTransmissionRangeLabel;
    private javax.swing.JTextField accessPointTransmissionRangeTextField;
    private javax.swing.JLabel joulesLabel;
    private javax.swing.JLabel metersLabel;
    // End of variables declaration//GEN-END:variables
    
}
